
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/cs/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 5.4.0-153-generic - x86_64
...
