/**
 * Thumbnail Service
 *
 * Manages server-side thumbnail generation jobs.
 * Thumbnails are generated by a headless browser worker to ensure
 * they accurately represent the visualization (no client tampering).
 */

const { Queue } = require("bullmq");
const { createLogger } = require("../utils/logger");

const log = createLogger("thumbnails");

// Redis connection config
const connection = {
  host: process.env.REDIS_HOST || "localhost",
  port: parseInt(process.env.REDIS_PORT || "6379"),
};

// Thumbnail queue
let thumbnailQueue = null;

/**
 * Get or create the thumbnail queue
 */
function getQueue() {
  if (!thumbnailQueue) {
    thumbnailQueue = new Queue("thumbnail", { connection });
    log.info("Thumbnail queue initialized");
  }
  return thumbnailQueue;
}

/**
 * Queue a thumbnail generation job for a file
 *
 * @param {object} options
 * @param {string} options.fileId - The file ID
 * @param {object} options.pool - Database pool
 * @param {string} options.viewId - Optional view configuration ID
 * @param {string} options.projectId - Optional project ID for access control
 * @param {number} options.priority - Job priority (1-10, higher = more urgent)
 * @returns {Promise<object>} - The queued job
 */
async function queueThumbnailJob({
  fileId,
  pool,
  viewId = null,
  projectId = null,
  priority = 5,
}) {
  const queue = getQueue();

  // Look up handler type from database (server-authoritative)
  // The column is 'file_type' which stores the file extension (e.g., 'vtp', 'nii')
  let handlerType = null;
  if (pool && fileId) {
    try {
      const result = await pool.query(
        "SELECT file_type FROM datasets WHERE id = $1",
        [fileId]
      );
      handlerType = result.rows[0]?.file_type;
    } catch (err) {
      log.warn(`Could not look up file_type for file ${fileId}:`, err.message);
    }
  }

  const jobData = {
    fileId,
    viewId: viewId || null,
    projectId: projectId || null,
    handlerType, // Server-determined handler type
    callbackUrl: `${
      process.env.API_URL || "http://localhost:3001"
    }/api/thumbnails/callback`,
    queuedAt: new Date().toISOString(),
  };

  const job = await queue.add("generate-thumbnail", jobData, {
    priority,
    attempts: 3,
    backoff: {
      type: "exponential",
      delay: 5000,
    },
    removeOnComplete: 100,
    removeOnFail: 50,
  });

  log.info(
    `Queued thumbnail job ${job.id} for file=${fileId}, view=${viewId}, type=${handlerType}`
  );

  return {
    jobId: job.id,
    fileId,
    viewId,
    handlerType,
    status: "queued",
  };
}

/**
 * Queue thumbnail jobs for all views of a file
 *
 * @param {object} pool - Database pool
 * @param {string} fileId - The file ID
 * @returns {Promise<object[]>} - Array of queued jobs
 */
async function queueThumbnailsForFile(pool, fileId) {
  // Get all active views for this file
  const result = await pool.query(
    `SELECT id FROM view_configurations
     WHERE dataset_id = $1 AND status = 'active'`,
    [fileId]
  );

  const jobs = [];
  for (const row of result.rows) {
    const job = await queueThumbnailJob({
      fileId,
      pool,
      viewId: row.id,
      priority: 3, // Lower priority for batch jobs
    });
    jobs.push(job);
  }

  // If no views exist, queue a job for the file itself
  // (will create a default view when rendered)
  if (jobs.length === 0) {
    const job = await queueThumbnailJob({ fileId, pool, priority: 5 });
    jobs.push(job);
  }

  log.info(`Queued ${jobs.length} thumbnail jobs for file ${fileId}`);
  return jobs;
}

/**
 * Handle thumbnail job completion callback
 *
 * @param {object} pool - Database pool
 * @param {object} result - Job result from worker
 * @param {function} broadcastFn - Optional function to broadcast updates via WebSocket
 */
async function handleThumbnailCallback(pool, result, broadcastFn = null) {
  const {
    jobId,
    success,
    storageKey,
    format,
    width,
    height,
    error,
    thumbnailType,
    fileId,
    viewId,
  } = result;

  if (!success) {
    log.error(`Thumbnail job ${jobId} failed: ${error}`);
    return { success: false, error };
  }

  // Handle file-level thumbnails (stored in datasets table)
  if (thumbnailType === "file" && fileId) {
    await pool.query(
      `UPDATE datasets
       SET thumbnail_key = $1, thumbnail_updated_at = NOW(), updated_at = NOW()
       WHERE id = $2`,
      [storageKey, fileId]
    );

    log.info(`File thumbnail saved for ${fileId}: ${storageKey}`);

    // Broadcast file thumbnail update to all connected clients
    if (broadcastFn) {
      broadcastFn("thumbnail:file-updated", { fileId, storageKey });
    }

    return { success: true, fileId, storageKey, type: "file" };
  }

  // Handle view-level thumbnails (stored in view_thumbnails table)
  if (thumbnailType === "view" && viewId) {
    // PostgreSQL UNIQUE constraint treats NULL as distinct, so ON CONFLICT won't work
    // for snapshot_id = NULL. Use atomic upsert with CTE to prevent race conditions
    // where a GET request could happen between DELETE and INSERT.
    await pool.query(
      `WITH deleted AS (
        DELETE FROM view_thumbnails
        WHERE view_config_id = $1 AND snapshot_id IS NULL
        RETURNING id
      )
      INSERT INTO view_thumbnails (view_config_id, storage_key, format, width, height)
      VALUES ($1, $2, $3, $4, $5)`,
      [viewId, storageKey, format, width, height]
    );

    log.info(`View thumbnail saved for ${viewId}: ${storageKey}`);

    // Broadcast view thumbnail update to all connected clients
    if (broadcastFn) {
      broadcastFn("thumbnail:view-updated", { viewId, storageKey, fileId });
    }

    return { success: true, viewId, storageKey, type: "view" };
  }

  // Fallback: parse from storage key (legacy behavior)
  const match = storageKey?.match(/thumbnails\/([^/]+)\//);
  const extractedId = match ? match[1] : null;

  if (!extractedId) {
    log.error(`Cannot determine ID from storage key: ${storageKey}`);
    return { success: false, error: "Invalid storage key" };
  }

  // Assume it's a view thumbnail for backward compatibility
  // Same atomic upsert pattern for NULL snapshot_id
  await pool.query(
    `WITH deleted AS (
      DELETE FROM view_thumbnails
      WHERE view_config_id = $1 AND snapshot_id IS NULL
      RETURNING id
    )
    INSERT INTO view_thumbnails (view_config_id, storage_key, format, width, height)
    VALUES ($1, $2, $3, $4, $5)`,
    [extractedId, storageKey, format, width, height]
  );

  log.info(`Thumbnail saved (legacy) for ${extractedId}: ${storageKey}`);

  if (broadcastFn) {
    broadcastFn("thumbnail:view-updated", { viewId: extractedId, storageKey });
  }

  return { success: true, viewId: extractedId, storageKey };
}

/**
 * Check if a thumbnail exists for a view
 *
 * @param {object} pool - Database pool
 * @param {string} viewId - View configuration ID
 * @returns {Promise<boolean>}
 */
async function hasThumbnail(pool, viewId) {
  const result = await pool.query(
    `SELECT 1 FROM view_thumbnails
     WHERE view_config_id = $1 AND snapshot_id IS NULL
     LIMIT 1`,
    [viewId]
  );
  return result.rows.length > 0;
}

/**
 * Check if a file has a thumbnail
 *
 * @param {object} pool - Database pool
 * @param {string} fileId - File/dataset ID
 * @returns {Promise<boolean>}
 */
async function hasFileThumbnail(pool, fileId) {
  const result = await pool.query(
    `SELECT 1 FROM datasets
     WHERE id = $1 AND thumbnail_key IS NOT NULL
     LIMIT 1`,
    [fileId]
  );
  return result.rows.length > 0;
}

/**
 * Get file thumbnail info
 *
 * @param {object} pool - Database pool
 * @param {string} fileId - File/dataset ID
 * @returns {Promise<object|null>}
 */
async function getFileThumbnailInfo(pool, fileId) {
  const result = await pool.query(
    `SELECT id, thumbnail_key, thumbnail_updated_at
     FROM datasets
     WHERE id = $1`,
    [fileId]
  );
  return result.rows[0] || null;
}

/**
 * Queue a file-level thumbnail (not view-specific)
 * Used when a file is uploaded and needs its initial thumbnail
 *
 * @param {object} options
 * @param {string} options.fileId - File ID
 * @param {object} options.pool - Database pool
 * @param {number} options.priority - Job priority
 * @returns {Promise<object>}
 */
async function queueFileThumbnailJob({ fileId, pool, priority = 5 }) {
  // File thumbnails don't have a viewId - they're rendered with default view
  return queueThumbnailJob({
    fileId,
    pool,
    viewId: null, // Important: null means this is a file-level thumbnail
    priority,
  });
}

/**
 * Check for files missing thumbnails and queue generation
 * Call this on server startup and periodically to catch missing thumbnails
 *
 * @param {object} pool - Database pool
 * @param {number} limit - Max files to process at once (default 50)
 * @returns {Promise<{queued: number, total: number}>}
 */
async function queueMissingFileThumbnails(pool, limit = 50) {
  try {
    // Find active files without thumbnails
    const result = await pool.query(
      `SELECT id, filename FROM datasets
       WHERE status = 'active'
         AND thumbnail_key IS NULL
       ORDER BY uploaded_at DESC
       LIMIT $1`,
      [limit]
    );

    if (result.rows.length === 0) {
      log.debug("No files missing thumbnails");
      return { queued: 0, total: 0 };
    }

    log.info(
      `Found ${result.rows.length} files missing thumbnails, queuing...`
    );

    let queued = 0;
    for (const file of result.rows) {
      try {
        await queueFileThumbnailJob({
          fileId: file.id,
          pool,
          priority: 2, // Low priority for background catch-up
        });
        queued++;
      } catch (err) {
        log.warn(
          `Failed to queue thumbnail for file ${file.id}: ${err.message}`
        );
      }
    }

    log.info(`Queued ${queued}/${result.rows.length} missing file thumbnails`);
    return { queued, total: result.rows.length };
  } catch (err) {
    log.error("Failed to check for missing thumbnails:", err.message);
    return { queued: 0, total: 0, error: err.message };
  }
}

/**
 * Get thumbnail info including last update time
 *
 * @param {object} pool - Database pool
 * @param {string} viewId - View configuration ID
 * @returns {Promise<object|null>} - Thumbnail info or null
 */
async function getThumbnailInfo(pool, viewId) {
  const result = await pool.query(
    `SELECT id, updated_at, created_at
     FROM view_thumbnails
     WHERE view_config_id = $1 AND snapshot_id IS NULL
     LIMIT 1`,
    [viewId]
  );
  return result.rows[0] || null;
}

/**
 * Check if thumbnail is stale (older than specified minutes)
 *
 * @param {object} pool - Database pool
 * @param {string} viewId - View configuration ID
 * @param {number} maxAgeMinutes - Max age in minutes before considered stale
 * @returns {Promise<boolean>} - true if stale or missing
 */
async function isThumbnailStale(pool, viewId, maxAgeMinutes = 30) {
  const info = await getThumbnailInfo(pool, viewId);
  if (!info) return true; // No thumbnail = stale

  const lastUpdate = new Date(info.updated_at || info.created_at);
  const ageMs = Date.now() - lastUpdate.getTime();
  const ageMinutes = ageMs / (1000 * 60);

  return ageMinutes > maxAgeMinutes;
}

// In-memory debounce tracking (cleared on server restart)
const recentlyQueued = new Map();
const DEBOUNCE_MS = 10000; // 10 seconds minimum between queue requests

/**
 * Queue thumbnail with debouncing to prevent excessive regeneration
 *
 * @param {object} options - Same as queueThumbnailJob
 * @param {number} debounceMs - Minimum ms between queue requests (default 30s)
 * @returns {Promise<object|null>} - Job info or null if debounced
 */
async function queueThumbnailJobDebounced(options, debounceMs = DEBOUNCE_MS) {
  const key = options.viewId || options.fileId;
  const now = Date.now();

  const lastQueued = recentlyQueued.get(key);
  if (lastQueued && now - lastQueued < debounceMs) {
    log.debug(
      `Debounced thumbnail queue for ${key} (last queued ${
        (now - lastQueued) / 1000
      }s ago)`
    );
    return null;
  }

  recentlyQueued.set(key, now);

  // Clean up old entries periodically
  if (recentlyQueued.size > 1000) {
    const cutoff = now - debounceMs * 2;
    for (const [k, v] of recentlyQueued) {
      if (v < cutoff) recentlyQueued.delete(k);
    }
  }

  return queueThumbnailJob(options);
}

/**
 * Queue thumbnail generation only if thumbnail is missing or stale
 *
 * @param {object} options - Same as queueThumbnailJob plus maxAgeMinutes
 * @returns {Promise<object|null>} - Job info or null if not needed
 */
async function queueThumbnailIfNeeded(options) {
  const { viewId, pool, maxAgeMinutes = 30 } = options;

  if (!viewId || !pool) {
    log.warn("queueThumbnailIfNeeded requires viewId and pool");
    return null;
  }

  const stale = await isThumbnailStale(pool, viewId, maxAgeMinutes);
  if (!stale) {
    log.debug(`Thumbnail for view ${viewId} is fresh, skipping regeneration`);
    return null;
  }

  return queueThumbnailJobDebounced(options);
}

module.exports = {
  // Queue operations
  queueThumbnailJob,
  queueThumbnailJobDebounced,
  queueThumbnailIfNeeded,
  queueThumbnailsForFile,
  queueFileThumbnailJob,
  queueMissingFileThumbnails,

  // Callback handling
  handleThumbnailCallback,

  // View thumbnail queries
  hasThumbnail,
  getThumbnailInfo,
  isThumbnailStale,

  // File thumbnail queries
  hasFileThumbnail,
  getFileThumbnailInfo,

  // Queue access
  getQueue,
};
